const ADD_INGREDIENT = 'ADD_INGREDIENT'
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
const SET_INGREDIENT = 'SET_INGREDIENT'
const INIT_INGREDIENTS = 'INIT_INGREDIENTS'
const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED'

const PURCHASE_BURGER = 'PURCHASE_BURGER'
const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'
const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
const PURCHASE_INIT = 'PURCHASE_INIT'

const FETCH_ORDERS = 'FETCH_ORDERS'
const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'

const AUTH_START = 'AUTH_START'
const AUTH_CHECK_INITIAL_STATE = 'AUTH_CHECK_INITIAL_STATE'
const AUTH_SUCCESS = 'AUTH_SUCCESS'
const AUTH_FAIL = 'AUTH_FAIL'
const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'
const AUTH_LOGOUT = 'AUTH_LOGOUT'
const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
const AUTH_USER = 'AUTH_USER'
const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'


export {
	ADD_INGREDIENT,
	REMOVE_INGREDIENT,
	SET_INGREDIENT,
	FETCH_INGREDIENT_FAILED,
	PURCHASE_BURGER_SUCCESS,
	PURCHASE_BURGER_FAILED,
	PURCHASE_BURGER_START,
	PURCHASE_INIT,
	FETCH_ORDERS_START,
	FETCH_ORDERS_SUCCESS,
	FETCH_ORDERS_FAIL,
	AUTH_START,
	AUTH_SUCCESS,
	AUTH_FAIL,
	AUTH_LOGOUT,
	SET_AUTH_REDIRECT_PATH,
	AUTH_INITIATE_LOGOUT,
	AUTH_CHECK_TIMEOUT,
	AUTH_USER,
	AUTH_CHECK_INITIAL_STATE,
	INIT_INGREDIENTS,
	PURCHASE_BURGER,
	FETCH_ORDERS
}
