const ADD_INGREDIENT = 'ADD_INGREDIENT'
const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
const SET_INGREDIENT = 'SET_INGREDIENT'
const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED'
const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED'
const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'



export {
	ADD_INGREDIENT,
	REMOVE_INGREDIENT,
	SET_INGREDIENT,
	FETCH_INGREDIENT_FAILED,
	PURCHASE_BURGER_SUCCESS,
	PURCHASE_BURGER_FAILED,
	PURCHASE_BURGER_START
}